FILTER_REGEX_EXCLUDE: (/examples/|docs/javascripts)
DISABLE:
  - COPYPASTE
  - CSS
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - SPELL_PROSELINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_STANDARD
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_KICS
REPOSITORY_TRUFFLEHOG_DISABLE_ERRORS_IF_LESS_THAN: 2
JAVASCRIPT_ES_CONFIG_FILE: LINTER_DEFAULT
PRINT_ALL_FILES: false
GITHUB_STATUS_REPORTER: false
