---
  version: 3
  jobs:
    node-12-jdk-8: 
      docker:
        - image: circleci/openjdk:8-jdk-buster-node-browsers
     # working_directory: ~/cli
      steps:
        - checkout:
        - run: 
            name: Install base tools
            command: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get -y install wget zip unzip && sudo apt-get clean && echo 'Installed wget zip unzip' 
        - run:
            name: Install dependencies
            command: npm install --unsafe-perm
        - run:
            name: Lint
            command: npm run lint
        - run:
            name: Compile
            command: npm run compile
        - run:
            name: Test & Code Coverage
            command: npm run test:coverage
        - run:
            name: Submitting code coverage to codecov
            command: |
              ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
              curl -s https://codecov.io/bash | bash
 
  workflows:
    version: 2
    "vscode-groovy-lint-build-test":
      jobs:
        - node-12-jdk-8
