name: Update check

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  go:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: Install node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          package-manager-cache: false
          node-version: 24

      - name: Install dependencies and link
        run: |
          npm ci
          npm link

      - name: Validate no changes
        run: |
          npm run dev:pre-commit
          git --no-pager diff
          [[ 0 -eq $(git status --porcelain | wc -l) ]]